### ISSUE TITLE
Hope add Stroke Position fix

### ISSUE THREAD

**Issue by emengweb** [luz-alphacode/paperjs-offset#1]
Can you add some staff like Stroke Position setting? I use Sketch for design UI, it has function like that:
[https://hz.ued.cat/storage/app/media/sc_20190425152412.png](https://hz.ued.cat/storage/app/media/sc_20190425152412.png)

Thanks!

**Comment by emengweb** [comment]
Now try to use offset and exclude, create a fake Stroke as Insider border and outside border :P

**Comment by luz-alphacode** [comment]
Well, the canvas use center stroke by default but provide no parameter to control it. But we can fake the result other than offset the path, because the stroke algorithm provided by the canvas api should be more efficient and robust. 
**The trick here is double the strokeWidth**.
For any path, to make a outer stroke, double the strokeWidth, and draw the path again without stroke, the composition is a path with outer stroke.
To make a inner stroke, double the strokeWidth, and make a clip, and the result will be a inner stroke.

And here is the way to acheive this by [paper.js](http://sketch.paperjs.org/#V/0.11.8/S/jZIxT8MwEIX/ipWlqRRSJ9kiMSGBmEAwMDQdXOcgVszZci5UIup/50LcqnQig6V8fnf37slTguoTkjp57YF0l2SJdu38/2XgkGtAgiBuxVZmQu4abNACCV8wQjiIZ0Vd/gKaFH5YSKcGBX/eDYaMwzqWZQsezDcwKiRDPs6YguvhzbTU1aKUf+idsy7UYrW3SverePVurD1dBGhXDR7XZ2clO/NFrq1DSBn7MqegcLCKIL0p59lyHbXVtba60J6lDW42wiByDoupWP34i5YcvPIQ8ofgRp9OQnfGtgHm/X2ZsafTiJ2YnS6VzIz30HIHCiPEOTHw0yB2dxEPSwsZhW6ka0PVPQczr1RdrjTDqyYyFjyN9I8Nqiy2nt3z+9gHUL13BmlI6u3u+AM=):
```javascript
view.center = [0, 0]

let p1 = new Path.Rectangle({
    position: [0, 0],
    size: [100, 100],
    strokeWidth: 20,
    strokeColor: 'black',
    fillColor: 'red'
})

let p2 = p1.clone()
p2.translate(-200, 0)
let p3 = p1.clone()
p3.translate(200, 0)

// inner stroke
let pInner = new paper.Group({ children: [p2, p2.clone()] })
pInner.clipped = true

// center stroke
p1.strokeWidth = 10

// outer stroke
let p3Fill = p3.clone()
p3Fill.strokeWidth = 0
let pOuter = new paper.Group({ children: [p3, p3Fill] })
```
![01](https://user-images.githubusercontent.com/39257644/56733445-c3d65300-6792-11e9-9636-a12f651f1b6d.jpg)

**Comment by luz-alphacode** [comment]
For size and performance concern, both paper.js and this extend library cannot make these algorithms too perfect like some native application, so the algorithms will always fail in some edge cases. But the api is implement natively and do not have these concern, their implementions should be much more robust and perfect.
So, in my opinion, if you can acheive these effects natively, do it natively.

**Comment by luz-alphacode** [comment]
Since the solution is offered and this function is beyond the scope of this utility, I'll close the issue. @emengweb
